CREATE DATABASE doingsdone
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title CHAR(64) UNIQUE NOT NULL,
  author INT NOT NULL
);

CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status TINYINT(1) DEFAULT 0,
  task_title CHAR(128) NOT NULL,
  file_path CHAR(128),
  task_expiration TIMESTAMP NOT NULL,
  author_id INT NOT NULL,
  project_id INT NOT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email CHAR(64) UNIQUE NOT NULL,
  name CHAR(64) NOT NULL,
  password CHAR(128) NOT NULL
);